#!/bin/sh
touch /var/log/blockdaemon.log
chown root:root /var/log/blockdaemon.log
chmod 644 /var/log/blockdaemon.log
project -s > /dev/null
systemctl daemon-reload
systemctl enable project.service
systemctl start project.service
